import Head from 'next/head'
import { Inter } from 'next/font/google'
import StudentItem from './StudentItem'

const inter = Inter({ subsets: ['latin'] })

export default function Home({allDatas}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
          crossOrigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossOrigin="anonymous"></link>
      </Head>
      <main>
        <div className="container my-3">
          <h1 className="text-center">Attendence Management</h1>
          <div className="attendence my-4 text-center">
            <table className="table">
              <thead>
                <tr>
                  <th scope="col">Roll No.</th>
                  <th scope="col">Name</th>
                  <th scope="col">Status</th>
                </tr>
              </thead>
              <tbody>
                <StudentItem allDatas={allDatas}/>
              </tbody>
            </table>
            <div className="mb-3 text-end">
              <button type="submit" className="btn btn-primary" id="submit_res">Submit</button>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  let myurl = "http://localhost:3000/"
  let data = await fetch(`${myurl}/studentData.json`)
  let allDatas = await data.json()
  // console.log(allDatas)

  return {
    props: { allDatas },
  }
}